### ISSUE TITLE
2021-07-30 스터디

### ISSUE THREAD

**Issue by rnjstjdgh** [algo-algo/WeaklyStudy#13]

**Comment by rnjstjdgh** [comment]
(### https://www.youtube.com/watch?v=J-VP0WFEQsY&t=2221s 강의 정리)
-------------------------------------------------------------------------
### Hystrix, Ribbon, Eureka에 대해 공부해 보기
-------------------------------------------------------------------------

### 1. Hystrix
* 사용 방법
    * Rest api를 구현한 메소드에 @HystrixCommand 어노테이션을 사용
    * ex> ![image](https://user-images.githubusercontent.com/41561652/127730455-689b62a8-a256-4280-822d-161ccfa03359.png)

* 기능
    1.  circuit breaker
        * @HystrixCommand이 달린 메소드를 호출하면 메소드의 실행 결과 성공 혹은 실패 발생 여부를 기록하고 통계를 낸다.
        * circuit 단위로 통계를 내서 open / close를 결정
        * 일정 시간동안 / 일정 개수 이상의 호출이 발생한 경우, 일정 비율 이상의 에러가 발생하면 circuit open(호출 차단)
        * 일정 시간 경과 후에 단 한개의 요청에 대해서 호출을 허용하며, 이 호출이 성공하면 circuit close(호출 허용)
        * Hystrix circuit breaker는 한 프로세스 내에서 주어진 commandkey 단위로 통계를 내고 동작함
            * ex> ![image](https://user-images.githubusercontent.com/41561652/127730457-0483114a-0d9b-4a82-9b8a-e6f9929d8390.png)
        * 따라서 연관된 서비스간의 차단 단위를 잘 결정해서 묶는게 중요(commandkey를 주지 않으면 메소드마다 각각 생성된다.)


    2.  Fallback
        * @HystrixCommand이 달린 메소드를 호출하면 실패했을 때 사용자가 지정한 메소드를 대신 실행
        * Fallback 이 동작하는 케이스
            * circuit open
            * Any Exception(HystrixBadRequestException 제외 - )
            * semaphore / ThreadPoolRejection(thread isolation과 연관)
            * Timeout
        * ex> ![image](/uploads/0b4e0bafb9080580cc9f3ed7c2714594/image.png)
        * Fallback code는 조심히 사용해야 한다.
            * 왜냐면, MSA는 연쇄적인 요청을 하게 되는데 특정 지점에서 Fallback이 잘못 발생하게 되면 시스템 장애를 감추게 될 수 있다.
        * HystrixBadRequestException 
            * 함수 호출한 클라이언트 코드에 잘못이 있는 경우 내 로직이 아니라 너가 잘못했다고 클라이언트 코드에 알려주는 용도로만 사용
            * circuit breaker의 통계 수집정보에서 빠지게 됨
            * ![image](/uploads/58166ec29d6126039609abb7e10d0768/image.png)
    3.  Thread isolation
        * @HystrixCommand이 달린 메소드를 호출하면 호출한 스레드 말고 다른 스레드에서 인터셉트 해서 실행
        * 두가지 선택지가 있음: 
            1. semaphore isolation
                * 서킷브레이커 마다 세마포어 붙어 있음 => 서킷브레이커와 연관된 서비스의 동시 최대 요청 수 지정 가능
                * ![image](/uploads/3ab93dba7db487f1d7d038dd064ef768/image.png)
            2. Thread isolation(default)
                * ![image](/uploads/71c506f111a60f9b94d1ddc7dda66db9/image.png)

    4.  Timeout
        * 특정시간 동안 메소드가 종료되지 않는 경우 Exception을 발생시킨다.
        * circuit breaker 단위로 지정 가능
-------------------------------------------------------------------------
### 2. Ribbon
* 개념(클라이언트 사이드 로드밸런서)
    * ![image](/uploads/61b83601b88ca22d32ab4f053a408023/image.png)
* spring cloud에선 Ribbon을 개발자가 명시적으로 사용하지 않음
    * spring cloud의 http 통신이 필요한 요소에 내장되어 있음
    * ex>
        * zull api gateway
        * restTemplate(@LoadBalanced)
        * Spring cloud feign: 선언적 http client
    * Eureka와 연동해서 사용됨
        * 즉, 서비스 군의 이름을 엔드포인트로 요청을 보내면 그 군과 매핑되는 실제 엔드포인트를 로드벨런싱 해 준다!

* Ribbon을 쓰면 좋은점
    * 로드벨런싱 개념을 완벽하게 프로그래밍 할 수 있음
    * ![image](/uploads/2c5600a52c1b85727982ff993a0d64f6/image.png)
    * spring cloud에선 이 타입의 bean을 정의하면 Ribbon client마다 커스텀 한 Ribbon을 장착할 수 있다.(fegien client같은것을 쓰면 디폴트로 부착되는데 이것을 커스터마이징 할 수 있다는 뜻임)

-------------------------------------------------------------------------
### 3. Eureka
* 개념
    * ![image](/uploads/80f9baacc53bea97669c478285d2cd62/image.png)
    * 이 개념이 Ribbon과 결합되어 서버 이름으로 호출을 하면 Ribbon이 해당 서버군을 대상으로 부하 분산해준다
    * `spring.application.name`에 등록된 이름으로 eureka server에 등록됨

* 특징
    *  spring application의 생명주기와 연동되어 같이 돌아간다.
    *  즉, application이 뜨면 자동으로 eureka server에 등록이 되고 
    *  주기적으로 HeartBeat를 보내 eureka server에 생존신고도 하고
    *  Server 종료 시 eureka 서버에 자신의 상태 변경(DOWN)혹은 자신의 목록 삭제
    *  이런것들이 별도 설정 없이 spring application 생명주기와 맞물려 자동으로 돌아간다.

* Ribbon 과의 연동
    * ![image](/uploads/9288c08039de66978127449a12bdc927/image.png)
    * Ribbon 입장에서는 Eureka가 없다면 별도 설정 기반으로 부하분산을 하지만
    * Ribbon이 뜰 때 Eureka가 있다면 설정 없이 Eureka와 연동해 부하분산 수행

    * 이렇게 되면 특정 서비스를 scale-out할 때 별도 설정 수정 없이 단순히 서비스를 하나 더 실행시키기만 하면 된다!
-----------------------------------------------
### 4. Zuul(API Gateway)

### Zuul에서는 비동기를 지원하지 않기 때문에 spring cloud 2점대 버전에서는 비동기 방식을 지원하기 위해 netty도입

* 개념
    * ![image](/uploads/0d898b6405015d9116f24402a61204ab/image.png)
*  특징
    * zuul은 api routing을 Hystrix, Ribbon, Eureka를 통해 구현했음
    * spring cloud와 가장 잘 통합되어 있는 api gateway
    * ![image](/uploads/9aaefad867ab446bd00b8dd3fbba3052/image.png)
        * 서버 군의 이름을 기준으로 라우팅
        * 라우팅 되는 서버 군은 자동으로 부하 분산 가능
        * 서버 군 단위로 자동으로 Hystrix 사용 가능(서킷브레이커 기능을 통해 api gateway와 뒷단의 서비스들 사이의 호출을 격리시켜 api gateway의 안정성을 도모 가능)
    * zuul에서는 서버 군 마다 Hystrix commandKey가 부여됨
    * 또한, zuul에서는 default isolation option이 semaphore로 설정되어 있음
    * ![image](/uploads/6ab4205a2d2051dc16fcaedc67d31719/image.png)
        * 서킷브레이커의 max semaphore를 결정하는 것이 뒷단에 서비스의 트래픽을 결정
        * 또한 이 수치로 인해 api gateway가 죽는 것을 방지
    * option을 Thread로 변경 가능
        * ![image](/uploads/78eec557ffbe3d95d796cbfd07f511d7/image.png)

-----------------------------------------------
### 5.  Server to Server 호출에 대한 고민
* ![image](/uploads/713106fbe39a531bc1eb19626da2f8ae/image.png)
1.  모든 통신은 gateway를 통해서?
    * 모든 통신을 하나의 진입점에서 통제가능(허락되지 않은 남의 호출 차단 가능-> filter)
    * 단점은, single point off failure 즉, GW가 죽으면 모든 통신 중단 / 모든 통신의 트래픽을 GW가 감당해야함

2.  내부 통신은 자기들끼리?
    * Eureka + Ribbon을 사용하면 서비스간 내부통신에서도 쉽게 scale-up가능
    * 특성은 1번과 반대


-----------------------------------------------
### 6.  Spring Cloud Feign
* ![image](/uploads/a56aa63cf2cfca3fc215f6da57db82ea/image.png)
* ![image](/uploads/5959c89ab0be00d0c24b7b4fffc0db13/image.png)
    * url생략하면 해당 서비스 군의 이름을 기준으로 Eureka + Ribbon이 붙어서 동작
    * Hystrix연동
        * ![image](/uploads/38b835a603d37149df811d6ac11d6a4c/image.png)
        * 이렇게 설정해 주면 메소드 하나하나 마다 Hystrix가 붙는다. 
            * 서버 군 이름 단위로 서킷브레이커 기능 / isolation / fallback / timeout 기능 사용 가능
            * 주의할 점은 Hystrix가 붙는 단위는 디폴트로 가져가기 보단 충분한 고민 후 적절히 묶어야 한다.
* 정리
    * ![image](/uploads/a30bde7724f420c5d1d99c6ed2003235/image.png)

**Comment by tpwls9494** [comment]
it기술노트
https://wikidocs.net/22366

프로그래머스 - 뮤직 플레이어 앱 프로젝트 구상
https://programmers.co.kr/assignments/18004/challenges/848
