### ISSUE TITLE
2021-08-14 스터디

### ISSUE THREAD

**Issue by rnjstjdgh** [algo-algo/WeaklyStudy#15]

**Comment by rnjstjdgh** [comment]
# 1.  Session & cookie 방식의 인증과 jwt 방식의 인증 차이

### Session 방식
* 로그인(인증) 후 서버 측에 Session을 저장하고 있음
* Session 속에는 유저 정보가 들어있음
* 해당 Session을 열어보기 위한 Session key가 클라이언트에 전달됨
* 클라이언트는 Session Key를 Cookie에 저장해 두고 매 요청 마다 헤더에 넣어서 보냄
* 서버는 클라이언트가 보낸 Session key를 가지고 Session 정보를 조회하고 이를 통해 User를 식별, 그에 맞는 인가 수행

### JWT 방식
* 로그인(인증) 후 서버 측에 정보를 저장하는 것이 아님, 서버는 JWT Token을 만든다.
* JWT Token에는 다음 정보가 있음
    1. Header: 암호화 방식 / 토큰 타입등의 정보
    2. payload: 토큰의 내용물(사용자 정보, 권한정보 등등..)
    3. SIGNATURE: [header + payload]를 암호화 한 내용
* 즉, JWT Token 속에 사용자에 대한 정보를 담고 이를 암호화 하여 클라이언트에 전달(서버는 정보를 저장하지 않음 => stateless)
* 클라이언트는 매 요청마다 JWT Token을 보내고 서버는 이를 검증하여 사용자 정보를 얻고 그에 맞는 인가 수행

**Comment by giantim** [comment]
클린 아키텍처: 소프트웨어 구조와 설계의 원칙 읽기
- 27장: 서비스 아키텍처를 나누기
- 28장: 테스트를 고려한 설계
- 29장: 임베디드 아키텍처를 설계할 때 관심사 분리하기

**Comment by YounggLee** [comment]
### CKA 준비
- CKA 시험 신청
- 모의 테스트 진행
